package com.alex.speedshare

import android.content.Context
import android.os.Build
import java.util.Locale

enum class AppLanguage(val storedValue: String) {
    SYSTEM("system"),
    SIMPLIFIED_CHINESE("zh"),
    JAPANESE("ja"),
    ENGLISH("en");

    companion object {
        fun fromStored(value: String?): AppLanguage =
            values().firstOrNull { it.storedValue == value } ?: SYSTEM
    }
}

enum class ResolvedLanguage(val htmlLanguageTag: String, val locale: Locale) {
    SIMPLIFIED_CHINESE("zh-CN", Locale.SIMPLIFIED_CHINESE),
    JAPANESE("ja", Locale.JAPANESE),
    ENGLISH("en", Locale.ENGLISH)
}

class Translator internal constructor(
    val language: ResolvedLanguage
) {
    fun text(key: String, vararg args: Any?): String {
        var result = Localization.table(language)[key]
            ?: Localization.table(ResolvedLanguage.ENGLISH)[key]
            ?: key
        args.forEachIndexed { index, value ->
            result = result.replace("{$index}", value?.toString().orEmpty())
        }
        return result
    }
}

object Localization {
    fun resolve(context: Context, setting: AppLanguage): ResolvedLanguage {
        if (setting != AppLanguage.SYSTEM) {
            return when (setting) {
                AppLanguage.SIMPLIFIED_CHINESE -> ResolvedLanguage.SIMPLIFIED_CHINESE
                AppLanguage.JAPANESE -> ResolvedLanguage.JAPANESE
                AppLanguage.ENGLISH -> ResolvedLanguage.ENGLISH
                AppLanguage.SYSTEM -> ResolvedLanguage.ENGLISH
            }
        }

        val locale = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            context.resources.configuration.locales[0]
        } else {
            @Suppress("DEPRECATION")
            context.resources.configuration.locale
        } ?: Locale.ENGLISH

        return when (locale.language.lowercase(Locale.ROOT)) {
            "zh" -> ResolvedLanguage.SIMPLIFIED_CHINESE
            "ja" -> ResolvedLanguage.JAPANESE
            else -> ResolvedLanguage.ENGLISH
        }
    }

    fun translator(context: Context, setting: AppLanguage): Translator =
        Translator(resolve(context, setting))

    fun translator(language: ResolvedLanguage): Translator = Translator(language)

    internal fun table(language: ResolvedLanguage): Map<String, String> = when (language) {
        ResolvedLanguage.ENGLISH -> ENGLISH
        ResolvedLanguage.JAPANESE -> JAPANESE
        ResolvedLanguage.SIMPLIFIED_CHINESE -> CHINESE
    }

    private val ENGLISH: Map<String, String> = mapOf(
        "app_subtitle" to "Fast local network sharing",
        "settings" to "Settings",
        "back" to "Back",
        "server_stopped" to "Server stopped",
        "choose_or_whole" to "Choose files or share the entire phone storage",
        "notification_permission_denied" to "Notification permission is off. The server can still run, but notification controls may not appear.",
        "server_started" to "Server started",
        "server_replacing" to "Stopping the previous server and replacing the shared content…",
        "server_starting" to "Starting server…",
        "permission_manage_files_prompt" to "Allow SpeedShareWeb to manage all files. Sharing will start automatically when you return.",
        "selected_files_ready" to "{0} files selected. Tap Start to share.",
        "no_readable_files" to "No readable files were received.",
        "share_files_unreadable" to "The share request was received, but none of its files could be read.",
        "incoming_auto_replaced" to "Received {0} shared files and replaced the current server.",
        "incoming_wait_manual" to "Received {0} files. Waiting for manual start.",
        "shortcut_whole_started" to "Whole-phone sharing started from a shortcut.",
        "quick_tile_whole_started" to "Whole-phone sharing started from Quick Settings.",
        "server_stop_action" to "Server stopped",
        "manage_files_return_start" to "Allow access to all files. Whole-phone sharing will start when you return.",
        "permission_granted" to "File management permission granted.",
        "settings_saved" to "Settings saved",
        "settings_auto_save_hint" to "Changes are saved automatically. You can return at any time.",
        "speed_upload" to "Upload",
        "speed_download" to "Download",
        "address_label" to "SpeedShareWeb address",
        "address_copied" to "Address copied",
        "qr_description" to "QR code for the SpeedShareWeb address",
        "scan_to_access" to "Scan to open",
        "collapse" to "Collapse",
        "choose_files" to "Choose files",
        "choose_files_sub" to "Quickly share selected content",
        "whole_phone" to "Entire phone",
        "whole_phone_sub" to "Browse, upload, and manage",
        "open_trash" to "Open SpeedShareWeb trash",
        "open_trash_sub" to "Restore or permanently delete items directly in the app",
        "trash_permission_prompt" to "Allow file management access, then the trash will open automatically.",
        "trash_open_failed" to "Could not open the system file manager.",
        "trash_manager_title" to "Recycle bin",
        "trash_manager_subtitle" to "Restore items, permanently delete them, or open the storage folder",
        "trash_empty" to "The recycle bin is empty",
        "trash_empty_sub" to "Items deleted through remote management will appear here.",
        "trash_item_count" to "{0} items",
        "trash_selected_count" to "{0} selected",
        "select_all" to "Select all",
        "clear_selection" to "Clear selection",
        "restore_selected" to "Restore to original",
        "delete_forever" to "Delete forever",
        "empty_trash" to "Empty recycle bin",
        "open_system_manager" to "Open system file manager",
        "trash_restore_done" to "Restored {0} items.",
        "trash_delete_done" to "Permanently deleted {0} items.",
        "trash_empty_done" to "Recycle bin emptied.",
        "trash_operation_failed" to "Operation failed: {0}",
        "trash_confirm_delete_title" to "Permanently delete selected items?",
        "trash_confirm_delete_body" to "This cannot be undone.",
        "trash_confirm_empty_title" to "Empty the recycle bin?",
        "trash_confirm_empty_body" to "All items will be permanently deleted and cannot be restored.",
        "cancel" to "Cancel",
        "confirm" to "Confirm",
        "original_location" to "Original: {0}",
        "folder" to "Folder",
        "file" to "File",
        "settings_credit" to "Edited and built by TokyoAlex.com",
        "custom_start" to "Custom start",
        "adjust_mode_permissions" to "Adjust mode and permissions",
        "mode_summary" to "{0} · {1} selected",
        "selected_count_short" to "{0} files",
        "expand" to "Expand",
        "selected_share" to "Selected files",
        "whole_directory" to "Entire storage",
        "allow_upload" to "Allow uploads",
        "allow_upload_sub" to "Browsers can upload to the current folder",
        "remote_management" to "Remote management",
        "remote_management_sub" to "Rename, copy, move, and use the trash",
        "lockscreen_protection" to "Screen-off protection",
        "lockscreen_protection_sub" to "Keep running only during active transfers",
        "replaced_server" to "Previous server replaced",
        "start_current" to "Start with these options",
        "replace_restart" to "Replace and restart",
        "no_ipv4" to "No local IPv4 address detected. Make sure the phone is connected to Wi-Fi.",
        "settings_subtitle" to "Compact, fast, and only the options you need",
        "language" to "Language",
        "language_sub" to "Used by the app, notifications, and browser page",
        "language_system" to "Follow system",
        "language_chinese" to "简体中文",
        "language_japanese" to "日本語",
        "language_english" to "English",
        "default_behavior" to "Default behavior",
        "default_share_mode" to "Default share mode",
        "selected_files" to "Selected files",
        "delete_to_trash" to "Move deletions to trash",
        "delete_to_trash_sub" to "Permanent deletion still asks for confirmation",
        "auto_start_share" to "Auto-start after system share",
        "auto_start_share_sub" to "Replace the current share immediately after receiving files",
        "auto_stop" to "Auto stop",
        "never" to "Never",
        "minutes_10" to "10 min",
        "minutes_30" to "30 min",
        "hour_1" to "1 hour",
        "network_port" to "Network and port",
        "preferred_port" to "Preferred port (1024–65535)",
        "auto_find_port" to "Find an available port automatically",
        "auto_find_port_sub" to "Try following ports if the preferred port is busy",
        "copy_after_start" to "Copy address after start",
        "copy_after_start_sub" to "Also applies to tiles, shortcuts, and system sharing",
        "system_shortcuts" to "System shortcuts",
        "add_quick_tile" to "Add Quick Settings tile",
        "request_pinned_success" to "Shortcut request sent. Confirm it in the system dialog.",
        "request_pinned_unsupported" to "This launcher cannot add a pinned shortcut automatically.",
        "add_whole_to_home" to "Add “Share entire phone” to Home screen",
        "version_tile_help" to "Version {0} · Tap the tile to start or stop; hold it to open Settings.",
        "port_range_error" to "Port must be between 1024 and 65535.",
        "save_settings" to "Save settings",
        "stop" to "Stop",
        "copy" to "Copy",
        "qr_code" to "QR code",
        "connections" to "Connections",
        "send" to "Send",
        "receive" to "Receive",
        "tasks" to "Tasks",
        "running" to "Running",
        "starting" to "Starting",
        "running_upload" to "Running · Uploads allowed",
        "running_readonly" to "Running · Read only",
        "stopped" to "Stopped",
        "tile_add_manual" to "Open Quick Settings, tap Edit, then add SpeedShareWeb manually.",
        "tile_added" to "Quick Settings tile added.",
        "tile_exists" to "The Quick Settings tile is already added.",
        "tile_not_added" to "The tile was not added.",
        "tile_package_error" to "Failed to add: component package mismatch.",
        "tile_request_progress" to "Another add-tile request is already in progress.",
        "tile_component_error" to "Failed to add: invalid tile component.",
        "tile_foreground_error" to "Keep SpeedShareWeb in the foreground and try again.",
        "tile_unsupported" to "The system cannot add tiles automatically.",
        "tile_result" to "Tile request result: {0}",
        "invalid_share_config" to "Start failed: no valid sharing configuration was received.",
        "cannot_read_share" to "Start failed: the shared files could not be read.",
        "unknown_error" to "Unknown error",
        "start_failed" to "Start failed: {0}",
        "port_only" to "Port {0}",
        "port_fallback" to "Preferred port {0} was busy; switched to {1}.",
        "server_started_detail" to "{0} · {1} · {2}ms",
        "waiting_lan" to "Server is running and waiting for a local network.",
        "background_timeout" to "The background time limit was reached, so the server stopped automatically.",
        "server_running_waiting" to "Server is still running and waiting for a local network.",
        "network_restored" to "Local network restored. The access address was updated.",
        "address_changed" to "The network address changed. Use the new address or QR code.",
        "idle_stopped" to "No device connected for a long time, so the server stopped automatically.",
        "notification_channel" to "SpeedShareWeb local server",
        "notification_channel_desc" to "Shows status and controls for the local network file server.",
        "mode_selected_count" to "Sharing {0} selected files",
        "mode_whole" to "Entire phone storage",
        "mode_upload" to "Uploads allowed",
        "mode_readonly" to "Read only",
        "mode_manage" to "Management allowed",
        "mode_server" to "Local network server",
        "notification_waiting" to "{0} · Waiting for local network",
        "notification_speed" to "{0} · {1} tasks · {2}",
        "notification_switching" to "SpeedShareWeb is switching",
        "notification_running" to "SpeedShareWeb is running",
        "open" to "Open",
        "copy_address" to "Copy address",
        "cannot_start_background" to "Unable to start background server: {0}",
        "unknown_device" to "Unknown device",
        "op_waiting" to "Waiting",
        "op_processing" to "Processing",
        "op_complete" to "Completed",
        "op_cancelled" to "Cancelled",
        "op_cancelling" to "Cancelling…",
        "op_server_stopping" to "Server is stopping; the task will be cancelled.",
        "op_copy" to "Copy",
        "op_move" to "Move",
        "op_trash" to "Move to trash",
        "op_delete" to "Permanent delete",
        "op_restore" to "Restore",
        "op_deleting" to "Deleting {0}",
        "op_trashing" to "Moving {0} to trash",
        "op_restoring" to "Restoring {0}",
        "op_skipped_same" to "Skipped {0} because it is already in that folder.",
        "op_skipped" to "Skipped {0}",
        "op_working" to "{0} {1}",
        "op_copy_delete_failed" to "Copy completed, but the original could not be deleted: {0}",
        "op_no_valid_files" to "No valid files.",
        "op_target_missing" to "Destination folder does not exist.",
        "op_target_self" to "A folder cannot be moved or copied into itself.",
        "op_target_inside" to "The destination cannot be inside the source folder.",
        "op_cancelled_exception" to "Operation cancelled.",
        "trash_file_missing" to "File does not exist.",
        "trash_repeat" to "The item is already in the trash.",
        "trash_source_delete_failed" to "Could not delete the original file.",
        "trash_metadata_failed" to "Could not write trash metadata.",
        "trash_entry_missing" to "Trash item does not exist.",
        "trash_metadata_corrupt" to "Trash metadata is damaged.",
        "trash_content_missing" to "Trash content does not exist.",
        "trash_original_invalid" to "Original path is invalid.",
        "trash_source_remove_failed" to "Could not remove the source item from trash.",
        "trash_overwrite_failed" to "Could not overwrite {0}.",
        "trash_create_dir_failed" to "Could not create folder {0}.",
        "unknown" to "Unknown",
        "web_selected_title" to "Selected share",
        "web_selected_sub" to "{0} files · Click an image, video, audio file, or PDF to preview it",
        "web_phone_title" to "Phone storage",
        "web_items" to "{0} items",
        "web_empty" to "Nothing to display here",
        "web_live" to "Live",
        "web_connections" to "Connections",
        "web_send_speed" to "Send speed",
        "web_receive_speed" to "Receive speed",
        "web_active_tasks" to "Active tasks",
        "web_no_transfers" to "No active transfers",
        "web_search" to "Search this page",
        "web_sort_name" to "Name",
        "web_sort_newest" to "Newest first",
        "web_sort_oldest" to "Oldest first",
        "web_sort_large" to "Largest first",
        "web_sort_small" to "Smallest first",
        "web_sort_type" to "Type",
        "web_grid" to "Grid",
        "web_list" to "List",
        "web_connecting" to "Connecting to SpeedShareWeb…",
        "web_close" to "Close",
        "web_download_original" to "Download original",
        "web_reconnected" to "Reconnected to SpeedShareWeb",
        "web_live_connected" to "Live connected",
        "web_reconnecting" to "Reconnecting",
        "web_connection_lost" to "Connection lost",
        "web_wait_server" to "Connection lost. Waiting for the phone server to return…",
        "web_visible" to "Showing {0} items",
        "web_selected_count" to "{0} items selected",
        "web_upload_file_progress" to "File {0}/{1}: {2} · {3}% · {4}/s",
        "web_network_failed" to "Network connection failed",
        "web_choose_or_drop" to "Choose or drop files first",
        "web_upload_done" to "Upload complete. Waiting for the page to update.",
        "web_upload_failed" to "Upload failed: {0}",
        "web_select_file_zip_folder" to "Select at least one file. Use ZIP for folders.",
        "web_select_items" to "Select files or folders first",
        "web_zip_name" to "ZIP file name",
        "web_no_download_url" to "The server did not return a download URL.",
        "web_zip_failed" to "ZIP preparation failed: {0}",
        "web_new_folder_name" to "New folder name",
        "web_folder_created" to "Folder created",
        "web_create_failed" to "Create failed: {0}",
        "web_manage_prompt" to "Manage {0}\nEnter an action: rename / copy / move / trash / delete",
        "web_new_name" to "New name",
        "web_rename_failed" to "Rename failed: {0}",
        "web_unsupported_action" to "Unsupported action",
        "web_choose_copy_target" to "Choose copy destination",
        "web_choose_move_target" to "Choose move destination",
        "web_loading_folders" to "Loading folders…",
        "web_target" to "Destination: /{0}",
        "web_target_hint" to "Choose this folder or open a subfolder",
        "web_use_here" to "Use this folder",
        "web_parent" to "Up",
        "web_open_folder" to "Open",
        "web_load_failed" to "Load failed: {0}",
        "web_conflict_prompt" to "Name conflict policy: rename=auto rename, overwrite=overwrite, skip=skip",
        "web_copy_started" to "Copy task started",
        "web_move_started" to "Move task started",
        "web_submit_failed" to "Could not submit task: {0}",
        "web_delete_permanent_confirm" to "Permanently delete the selected items? This cannot be undone.",
        "web_delete_trash_confirm" to "Move the selected items to the SpeedShareWeb trash?",
        "web_delete_started" to "Delete task started",
        "web_delete_failed" to "Delete failed: {0}",
        "web_trash" to "SpeedShareWeb trash",
        "web_loading" to "Loading…",
        "web_trash_count" to "{0} items in trash",
        "web_restore_hint" to "Restore uses automatic rename and does not overwrite existing files",
        "web_empty_trash" to "Trash is empty",
        "web_original_location" to "Original: /{0} · {1} · {2}",
        "web_restore" to "Restore",
        "web_delete_forever" to "Delete forever",
        "web_empty_trash_action" to "Empty trash",
        "web_restore_started" to "Restore task started",
        "web_restore_failed" to "Restore failed: {0}",
        "web_delete_trash_item_confirm" to "Permanently delete this trash item?",
        "web_empty_trash_confirm" to "Permanently empty the SpeedShareWeb trash?",
        "web_empty_failed" to "Empty failed: {0}",
        "web_task_center" to "File operation tasks",
        "web_no_operations" to "No file operation tasks",
        "web_cancel" to "Cancel",
        "web_cancel_failed" to "Cancel failed: {0}",
        "web_device_offline" to "Device offline",
        "web_network_offline" to "This device is offline",
        "web_manage" to "Manage",
        "web_folder" to "Folder",
        "web_video" to "Video",
        "web_audio" to "Audio",
        "web_open" to "Open",
        "web_preview" to "Preview",
        "web_download" to "Download",
        "web_new_folder" to "New folder",
        "web_task_center_short" to "Tasks",
        "web_readonly_hint" to "Remote management is off. You can browse, preview, download, and create ZIP files.",
        "web_move" to "Move",
        "web_move_trash" to "Move to trash",
        "web_permanent_delete" to "Permanent delete",
        "web_management_title" to "Selection and file management",
        "web_batch_download_title" to "Batch download",
        "web_batch_download_hint" to "Select files, then download them separately or as one ZIP file.",
        "web_current_folder" to "Current folder: /{0}",
        "web_select_all" to "Select all / clear",
        "web_download_separately" to "Download separately",
        "web_zip_fast" to "Fast ZIP",
        "web_zip_compress" to "Compressed ZIP",
        "web_clear_selection" to "Clear selection",
        "web_file_management" to "File management",
        "web_internal_storage" to "Internal storage",
        "web_upload_here" to "Upload to this folder",
        "web_upload_hint" to "Choose multiple files or drag files here",
        "web_choose_files" to "Choose files",
        "web_start_upload" to "Start upload",
        "web_no_files_selected" to "No files selected",
        "web_state_queued" to "Queued",
        "web_state_running" to "Running",
        "web_state_completed" to "Completed",
        "web_state_failed" to "Failed",
        "web_state_cancelled" to "Cancelled"
    )

    private val JAPANESE: Map<String, String> = mapOf(
        "app_subtitle" to "高速ローカルネットワーク共有",
        "settings" to "設定",
        "back" to "戻る",
        "server_stopped" to "サーバーは停止しています",
        "choose_or_whole" to "ファイルを選択するか、端末全体を共有してください",
        "notification_permission_denied" to "通知が許可されていません。サーバーは動作しますが、通知欄の操作が表示されない場合があります。",
        "server_started" to "サーバーを起動しました",
        "server_replacing" to "前のサーバーを停止し、共有内容を切り替えています…",
        "server_starting" to "サーバーを起動しています…",
        "permission_manage_files_prompt" to "SpeedShareWeb に「すべてのファイルの管理」を許可してください。戻ると自動的に共有を開始します。",
        "selected_files_ready" to "{0}件のファイルを選択しました。「開始」をタップすると共有できます。",
        "no_readable_files" to "読み取り可能なファイルを受信できませんでした。",
        "share_files_unreadable" to "共有リクエストを受信しましたが、ファイルを読み取れませんでした。",
        "incoming_auto_replaced" to "共有された{0}件のファイルを受信し、現在のサーバーを切り替えました。",
        "incoming_wait_manual" to "{0}件のファイルを受信しました。設定に従い、手動での開始を待っています。",
        "shortcut_whole_started" to "ショートカットから端末全体の共有を開始しました。",
        "quick_tile_whole_started" to "クイック設定から端末全体の共有を開始しました。",
        "server_stop_action" to "サーバーを停止しました",
        "manage_files_return_start" to "「すべてのファイルの管理」を許可してください。戻ると端末全体の共有を開始します。",
        "permission_granted" to "ファイル管理権限を取得しました。",
        "settings_saved" to "設定を保存しました",
        "settings_auto_save_hint" to "変更内容は自動保存されます。いつでも戻れます。",
        "speed_upload" to "アップロード",
        "speed_download" to "ダウンロード",
        "address_label" to "SpeedShareWeb アドレス",
        "address_copied" to "アドレスをコピーしました",
        "qr_description" to "SpeedShareWeb アクセス用QRコード",
        "scan_to_access" to "スキャンしてアクセス",
        "collapse" to "閉じる",
        "choose_files" to "ファイルを選択",
        "choose_files_sub" to "選択した内容をすぐに共有",
        "whole_phone" to "端末全体",
        "whole_phone_sub" to "閲覧・アップロード・管理",
        "open_trash" to "SpeedShareWeb ゴミ箱を開く",
        "open_trash_sub" to "アプリ内で復元・完全削除・一括管理ができます",
        "trash_permission_prompt" to "ファイル管理権限を許可すると、ゴミ箱を自動的に開きます。",
        "trash_open_failed" to "システムのファイル管理画面を開けませんでした。",
        "trash_manager_title" to "ゴミ箱",
        "trash_manager_subtitle" to "復元・完全削除・保存フォルダの確認ができます",
        "trash_empty" to "ゴミ箱は空です",
        "trash_empty_sub" to "リモート管理で削除した項目がここに表示されます。",
        "trash_item_count" to "{0}件",
        "trash_selected_count" to "{0}件選択中",
        "select_all" to "すべて選択",
        "clear_selection" to "選択解除",
        "restore_selected" to "元の場所へ復元",
        "delete_forever" to "完全に削除",
        "empty_trash" to "ゴミ箱を空にする",
        "open_system_manager" to "システムのファイル管理を開く",
        "trash_restore_done" to "{0}件を復元しました。",
        "trash_delete_done" to "{0}件を完全に削除しました。",
        "trash_empty_done" to "ゴミ箱を空にしました。",
        "trash_operation_failed" to "操作に失敗しました：{0}",
        "trash_confirm_delete_title" to "選択した項目を完全に削除しますか？",
        "trash_confirm_delete_body" to "この操作は元に戻せません。",
        "trash_confirm_empty_title" to "ゴミ箱を空にしますか？",
        "trash_confirm_empty_body" to "すべての項目が完全に削除され、復元できなくなります。",
        "cancel" to "キャンセル",
        "confirm" to "実行",
        "original_location" to "元の場所：{0}",
        "folder" to "フォルダ",
        "file" to "ファイル",
        "settings_credit" to "TokyoAlex.com により編集・制作",
        "custom_start" to "カスタム起動",
        "adjust_mode_permissions" to "モードと権限を調整",
        "mode_summary" to "{0}・選択済み {1}件",
        "selected_count_short" to "{0}ファイル",
        "expand" to "展開",
        "selected_share" to "選択ファイル",
        "whole_directory" to "ストレージ全体",
        "allow_upload" to "アップロードを許可",
        "allow_upload_sub" to "ブラウザから現在のフォルダへアップロードできます",
        "remote_management" to "リモート管理",
        "remote_management_sub" to "名前変更・コピー・移動・ゴミ箱を利用できます",
        "lockscreen_protection" to "画面オフ時の保護",
        "lockscreen_protection_sub" to "転送中のみ動作を維持します",
        "replaced_server" to "前のサーバーを切り替えました",
        "start_current" to "現在の設定で開始",
        "replace_restart" to "切り替えて再起動",
        "no_ipv4" to "ローカルIPv4アドレスを検出できません。端末がWi-Fiに接続されているか確認してください。",
        "settings_subtitle" to "コンパクトで高速、必要な項目だけ",
        "language" to "言語",
        "language_sub" to "アプリ・通知・ブラウザ画面に使用します",
        "language_system" to "システムに従う",
        "language_chinese" to "简体中文",
        "language_japanese" to "日本語",
        "language_english" to "English",
        "default_behavior" to "既定の動作",
        "default_share_mode" to "既定の共有モード",
        "selected_files" to "選択ファイル",
        "delete_to_trash" to "削除時にゴミ箱へ移動",
        "delete_to_trash_sub" to "完全削除時は引き続き確認します",
        "auto_start_share" to "システム共有後に自動開始",
        "auto_start_share_sub" to "ファイル受信後、現在の共有をすぐに切り替えます",
        "auto_stop" to "自動停止",
        "never" to "停止しない",
        "minutes_10" to "10分",
        "minutes_30" to "30分",
        "hour_1" to "1時間",
        "network_port" to "ネットワークとポート",
        "preferred_port" to "優先ポート（1024～65535）",
        "auto_find_port" to "使用可能なポートを自動検索",
        "auto_find_port_sub" to "優先ポートが使用中の場合、次のポートを試します",
        "copy_after_start" to "起動後にアドレスをコピー",
        "copy_after_start_sub" to "タイル・ショートカット・システム共有にも適用します",
        "system_shortcuts" to "システムショートカット",
        "add_quick_tile" to "クイック設定タイルを追加",
        "request_pinned_success" to "ショートカットの追加をリクエストしました。システムの画面で確認してください。",
        "request_pinned_unsupported" to "現在のホームアプリはショートカットの自動追加に対応していません。",
        "add_whole_to_home" to "「端末全体を共有」をホーム画面に追加",
        "version_tile_help" to "バージョン {0}・タイルをタップして開始／停止、長押しで設定を開きます。",
        "port_range_error" to "ポートは1024～65535の範囲で指定してください。",
        "save_settings" to "設定を保存",
        "stop" to "停止",
        "copy" to "コピー",
        "qr_code" to "QRコード",
        "connections" to "接続",
        "send" to "送信",
        "receive" to "受信",
        "tasks" to "タスク",
        "running" to "実行中",
        "starting" to "起動中",
        "running_upload" to "実行中・アップロード可",
        "running_readonly" to "実行中・読み取り専用",
        "stopped" to "停止中",
        "tile_add_manual" to "クイック設定を開き、「編集」から SpeedShareWeb を手動で追加してください。",
        "tile_added" to "クイック設定タイルを追加しました。",
        "tile_exists" to "クイック設定タイルはすでに追加されています。",
        "tile_not_added" to "タイルは追加されませんでした。",
        "tile_package_error" to "追加に失敗しました：コンポーネントのパッケージが一致しません。",
        "tile_request_progress" to "タイル追加のリクエストがすでに進行中です。",
        "tile_component_error" to "追加に失敗しました：タイルの設定が正しくありません。",
        "tile_foreground_error" to "SpeedShareWeb を前面に表示したまま、もう一度お試しください。",
        "tile_unsupported" to "このシステムはタイルの自動追加に対応していません。",
        "tile_result" to "タイル追加結果：{0}",
        "invalid_share_config" to "起動に失敗しました：有効な共有設定を受信できませんでした。",
        "cannot_read_share" to "起動に失敗しました：共有されたファイルを読み取れません。",
        "unknown_error" to "不明なエラー",
        "start_failed" to "起動に失敗しました：{0}",
        "port_only" to "ポート {0}",
        "port_fallback" to "優先ポート {0} は使用中のため、{1} に切り替えました。",
        "server_started_detail" to "{0}・{1}・{2}ms",
        "waiting_lan" to "サーバーを起動しました。ローカルネットワークへの接続を待っています。",
        "background_timeout" to "バックグラウンド実行時間の上限に達したため、サーバーを自動停止しました。",
        "server_running_waiting" to "サーバーは実行中です。ローカルネットワークへの接続を待っています。",
        "network_restored" to "ローカルネットワークが復旧し、アクセス先を更新しました。",
        "address_changed" to "ネットワークアドレスが変わりました。新しいアドレスまたはQRコードを使用してください。",
        "idle_stopped" to "長時間接続がなかったため、サーバーを自動停止しました。",
        "notification_channel" to "SpeedShareWeb ローカルサーバー",
        "notification_channel_desc" to "ローカルネットワークファイルサーバーの状態と操作を表示します。",
        "mode_selected_count" to "選択した{0}件を共有",
        "mode_whole" to "端末ストレージ全体",
        "mode_upload" to "アップロード可",
        "mode_readonly" to "読み取り専用",
        "mode_manage" to "管理可",
        "mode_server" to "ローカルネットワークサーバー",
        "notification_waiting" to "{0}・ローカルネットワーク待機中",
        "notification_speed" to "{0}・{1}件のタスク・{2}",
        "notification_switching" to "SpeedShareWeb を切り替えています",
        "notification_running" to "SpeedShareWeb 実行中",
        "open" to "開く",
        "copy_address" to "アドレスをコピー",
        "cannot_start_background" to "バックグラウンドサーバーを起動できません：{0}",
        "unknown_device" to "不明な端末",
        "op_waiting" to "実行待ち",
        "op_processing" to "処理中",
        "op_complete" to "完了",
        "op_cancelled" to "キャンセル済み",
        "op_cancelling" to "キャンセルしています…",
        "op_server_stopping" to "サーバーを停止中です。タスクをキャンセルします。",
        "op_copy" to "コピー",
        "op_move" to "移動",
        "op_trash" to "ゴミ箱へ移動",
        "op_delete" to "完全削除",
        "op_restore" to "復元",
        "op_deleting" to "{0} を削除しています",
        "op_trashing" to "{0} をゴミ箱へ移動しています",
        "op_restoring" to "{0} を復元しています",
        "op_skipped_same" to "{0} は同じフォルダにあるためスキップしました。",
        "op_skipped" to "{0} をスキップしました",
        "op_working" to "{1} を{0}中",
        "op_copy_delete_failed" to "コピーは完了しましたが、元ファイルを削除できませんでした：{0}",
        "op_no_valid_files" to "有効なファイルがありません。",
        "op_target_missing" to "移動先フォルダが存在しません。",
        "op_target_self" to "フォルダを自身の中へ移動またはコピーすることはできません。",
        "op_target_inside" to "移動先を元フォルダの内側に指定することはできません。",
        "op_cancelled_exception" to "操作がキャンセルされました。",
        "trash_file_missing" to "ファイルが存在しません。",
        "trash_repeat" to "すでにゴミ箱に入っています。",
        "trash_source_delete_failed" to "元ファイルを削除できませんでした。",
        "trash_metadata_failed" to "ゴミ箱のメタデータを書き込めませんでした。",
        "trash_entry_missing" to "ゴミ箱の項目が存在しません。",
        "trash_metadata_corrupt" to "ゴミ箱のメタデータが破損しています。",
        "trash_content_missing" to "ゴミ箱の内容が存在しません。",
        "trash_original_invalid" to "元のパスが無効です。",
        "trash_source_remove_failed" to "ゴミ箱内の元ファイルを削除できませんでした。",
        "trash_overwrite_failed" to "{0} を上書きできませんでした。",
        "trash_create_dir_failed" to "フォルダ {0} を作成できませんでした。",
        "unknown" to "不明",
        "web_selected_title" to "選択ファイル共有",
        "web_selected_sub" to "{0}件・画像、動画、音声、PDFはクリックしてプレビューできます",
        "web_phone_title" to "端末ストレージ",
        "web_items" to "{0}件",
        "web_empty" to "表示できる内容がありません",
        "web_live" to "リアルタイム接続中",
        "web_connections" to "接続",
        "web_send_speed" to "送信速度",
        "web_receive_speed" to "受信速度",
        "web_active_tasks" to "実行中のタスク",
        "web_no_transfers" to "転送中のファイルはありません",
        "web_search" to "このページを検索",
        "web_sort_name" to "名前順",
        "web_sort_newest" to "新しい順",
        "web_sort_oldest" to "古い順",
        "web_sort_large" to "サイズが大きい順",
        "web_sort_small" to "サイズが小さい順",
        "web_sort_type" to "種類順",
        "web_grid" to "グリッド",
        "web_list" to "リスト",
        "web_connecting" to "SpeedShareWeb に接続しています…",
        "web_close" to "閉じる",
        "web_download_original" to "元ファイルをダウンロード",
        "web_reconnected" to "SpeedShareWeb に再接続しました",
        "web_live_connected" to "リアルタイム接続済み",
        "web_reconnecting" to "再接続中",
        "web_connection_lost" to "接続が切れました",
        "web_wait_server" to "接続が切れました。端末側のサーバー復旧を待っています…",
        "web_visible" to "{0}件を表示中",
        "web_selected_count" to "{0}件を選択中",
        "web_upload_file_progress" to "{0}/{1}件目：{2}・{3}%・{4}/s",
        "web_network_failed" to "ネットワーク接続に失敗しました",
        "web_choose_or_drop" to "先にファイルを選択するか、ここへドロップしてください",
        "web_upload_done" to "アップロードが完了しました。ページの自動更新を待っています。",
        "web_upload_failed" to "アップロードに失敗しました：{0}",
        "web_select_file_zip_folder" to "ファイルを1件以上選択してください。フォルダはZIPでダウンロードしてください。",
        "web_select_items" to "ファイルまたはフォルダを選択してください",
        "web_zip_name" to "ZIPファイル名",
        "web_no_download_url" to "サーバーからダウンロードURLが返されませんでした。",
        "web_zip_failed" to "ZIPの準備に失敗しました：{0}",
        "web_new_folder_name" to "新しいフォルダ名",
        "web_folder_created" to "フォルダを作成しました",
        "web_create_failed" to "作成に失敗しました：{0}",
        "web_manage_prompt" to "{0} を管理\n操作を入力：rename / copy / move / trash / delete",
        "web_new_name" to "新しい名前",
        "web_rename_failed" to "名前の変更に失敗しました：{0}",
        "web_unsupported_action" to "対応していない操作です",
        "web_choose_copy_target" to "コピー先を選択",
        "web_choose_move_target" to "移動先を選択",
        "web_loading_folders" to "フォルダを読み込んでいます…",
        "web_target" to "移動先：/{0}",
        "web_target_hint" to "このフォルダを選択するか、子フォルダを開いてください",
        "web_use_here" to "このフォルダを使用",
        "web_parent" to "上へ",
        "web_open_folder" to "開く",
        "web_load_failed" to "読み込みに失敗しました：{0}",
        "web_conflict_prompt" to "同名ファイルの処理：rename=自動改名、overwrite=上書き、skip=スキップ",
        "web_copy_started" to "コピーを開始しました",
        "web_move_started" to "移動を開始しました",
        "web_submit_failed" to "タスクを開始できませんでした：{0}",
        "web_delete_permanent_confirm" to "選択した内容を完全に削除します。元に戻せません。続行しますか？",
        "web_delete_trash_confirm" to "選択した内容を SpeedShareWeb のゴミ箱へ移動しますか？",
        "web_delete_started" to "削除を開始しました",
        "web_delete_failed" to "削除に失敗しました：{0}",
        "web_trash" to "SpeedShareWeb ゴミ箱",
        "web_loading" to "読み込み中…",
        "web_trash_count" to "ゴミ箱内：{0}件",
        "web_restore_hint" to "復元時は自動的に名前を変更し、既存ファイルを上書きしません",
        "web_empty_trash" to "ゴミ箱は空です",
        "web_original_location" to "元の場所：/{0}・{1}・{2}",
        "web_restore" to "復元",
        "web_delete_forever" to "完全削除",
        "web_empty_trash_action" to "ゴミ箱を空にする",
        "web_restore_started" to "復元を開始しました",
        "web_restore_failed" to "復元に失敗しました：{0}",
        "web_delete_trash_item_confirm" to "このゴミ箱項目を完全に削除しますか？",
        "web_empty_trash_confirm" to "SpeedShareWeb のゴミ箱を完全に空にしますか？",
        "web_empty_failed" to "ゴミ箱を空にできませんでした：{0}",
        "web_task_center" to "ファイル操作タスク",
        "web_no_operations" to "ファイル操作タスクはありません",
        "web_cancel" to "キャンセル",
        "web_cancel_failed" to "キャンセルに失敗しました：{0}",
        "web_device_offline" to "端末はオフラインです",
        "web_network_offline" to "この端末はネットワークに接続されていません",
        "web_manage" to "管理",
        "web_folder" to "フォルダ",
        "web_video" to "動画",
        "web_audio" to "音声",
        "web_open" to "開く",
        "web_preview" to "プレビュー",
        "web_download" to "ダウンロード",
        "web_new_folder" to "新規フォルダ",
        "web_task_center_short" to "タスク",
        "web_readonly_hint" to "リモート管理はオフです。閲覧、プレビュー、ダウンロード、ZIP作成が可能です。",
        "web_move" to "移動",
        "web_move_trash" to "ゴミ箱へ",
        "web_permanent_delete" to "完全削除",
        "web_management_title" to "複数選択とファイル管理",
        "web_batch_download_title" to "一括ダウンロード",
        "web_batch_download_hint" to "ファイルを選択し、個別またはZIPでまとめてダウンロードできます。",
        "web_current_folder" to "現在のフォルダ：/{0}",
        "web_select_all" to "すべて選択／解除",
        "web_download_separately" to "個別ダウンロード",
        "web_zip_fast" to "高速ZIP",
        "web_zip_compress" to "圧縮ZIP",
        "web_clear_selection" to "選択を解除",
        "web_file_management" to "ファイル管理",
        "web_internal_storage" to "内部ストレージ",
        "web_upload_here" to "現在のフォルダへアップロード",
        "web_upload_hint" to "複数ファイルを選択するか、ここへドラッグできます",
        "web_choose_files" to "ファイルを選択",
        "web_start_upload" to "アップロード開始",
        "web_no_files_selected" to "ファイルが選択されていません",
        "web_state_queued" to "待機中",
        "web_state_running" to "実行中",
        "web_state_completed" to "完了",
        "web_state_failed" to "失敗",
        "web_state_cancelled" to "キャンセル済み"
    )

    private val CHINESE: Map<String, String> = mapOf(
        "app_subtitle" to "极速局域网分享",
        "settings" to "设置",
        "back" to "返回",
        "server_stopped" to "服务器已停止",
        "choose_or_whole" to "请选择文件，或一键分享整个手机目录",
        "notification_permission_denied" to "通知权限未开启；服务器仍可运行，但通知栏控制可能不显示。",
        "server_started" to "服务器已启动",
        "server_replacing" to "正在自动关闭上一个服务器并替换分享内容…",
        "server_starting" to "正在启动服务器…",
        "permission_manage_files_prompt" to "请允许 SpeedShareWeb 管理所有文件；返回后会自动启动。",
        "selected_files_ready" to "已选择 {0} 个文件；点击启动即可分享。",
        "no_readable_files" to "没有收到可读取的文件。",
        "share_files_unreadable" to "收到分享请求，但无法读取其中的文件。",
        "incoming_auto_replaced" to "已接收系统分享的 {0} 个文件并自动替换服务器。",
        "incoming_wait_manual" to "已接收 {0} 个文件；根据设置等待手动启动。",
        "shortcut_whole_started" to "已从快捷方式启动整个手机共享。",
        "quick_tile_whole_started" to "已从快捷设置启动整个手机共享。",
        "server_stop_action" to "服务器已停止",
        "manage_files_return_start" to "请允许管理所有文件；返回后会自动启动整个手机共享。",
        "permission_granted" to "已获得文件管理权限。",
        "settings_saved" to "设置已保存",
        "settings_auto_save_hint" to "所有修改都会自动保存，可以随时返回。",
        "speed_upload" to "上传",
        "speed_download" to "下载",
        "address_label" to "SpeedShareWeb 地址",
        "address_copied" to "地址已复制",
        "qr_description" to "SpeedShareWeb 访问地址二维码",
        "scan_to_access" to "扫码访问",
        "collapse" to "收起",
        "choose_files" to "选择文件",
        "choose_files_sub" to "快速分享已选内容",
        "whole_phone" to "整个手机",
        "whole_phone_sub" to "浏览、上传与管理",
        "open_trash" to "打开 SpeedShareWeb 回收站",
        "open_trash_sub" to "可在应用内恢复、永久删除和批量管理",
        "trash_permission_prompt" to "请允许文件管理权限，返回后会自动打开回收站。",
        "trash_open_failed" to "无法打开手机系统文件管理器。",
        "trash_manager_title" to "回收站",
        "trash_manager_subtitle" to "可恢复、永久删除，或打开系统存储目录",
        "trash_empty" to "回收站是空的",
        "trash_empty_sub" to "通过远程管理删除的内容会显示在这里。",
        "trash_item_count" to "共 {0} 项",
        "trash_selected_count" to "已选 {0} 项",
        "select_all" to "全选",
        "clear_selection" to "取消全选",
        "restore_selected" to "恢复到原位置",
        "delete_forever" to "永久删除",
        "empty_trash" to "清空回收站",
        "open_system_manager" to "打开系统文件管理器",
        "trash_restore_done" to "已恢复 {0} 项。",
        "trash_delete_done" to "已永久删除 {0} 项。",
        "trash_empty_done" to "回收站已清空。",
        "trash_operation_failed" to "操作失败：{0}",
        "trash_confirm_delete_title" to "永久删除已选内容？",
        "trash_confirm_delete_body" to "删除后无法恢复。",
        "trash_confirm_empty_title" to "清空回收站？",
        "trash_confirm_empty_body" to "所有内容都会被永久删除，且无法恢复。",
        "cancel" to "取消",
        "confirm" to "确定",
        "original_location" to "原位置：{0}",
        "folder" to "文件夹",
        "file" to "文件",
        "settings_credit" to "由 TokyoAlex.com 编辑与制作",
        "custom_start" to "自定义启动",
        "adjust_mode_permissions" to "调整模式与权限",
        "mode_summary" to "{0} · 已选 {1} 项",
        "selected_count_short" to "{0}个文件",
        "expand" to "展开",
        "selected_share" to "单独文件",
        "whole_directory" to "整个目录",
        "allow_upload" to "允许上传",
        "allow_upload_sub" to "浏览器可上传到当前目录",
        "remote_management" to "远程管理",
        "remote_management_sub" to "重命名、复制、移动与回收站",
        "lockscreen_protection" to "锁屏保护",
        "lockscreen_protection_sub" to "仅在实际传输时保持运行",
        "replaced_server" to "已替换上一个服务器",
        "start_current" to "按当前选项启动",
        "replace_restart" to "替换并重新启动",
        "no_ipv4" to "未检测到局域网 IPv4 地址，请确认手机已连接 Wi-Fi。",
        "settings_subtitle" to "紧凑、快速、只保留必要选项",
        "language" to "语言",
        "language_sub" to "用于应用、通知和浏览器页面",
        "language_system" to "跟随系统",
        "language_chinese" to "简体中文",
        "language_japanese" to "日本語",
        "language_english" to "English",
        "default_behavior" to "默认行为",
        "default_share_mode" to "默认分享模式",
        "selected_files" to "单独文件",
        "delete_to_trash" to "删除进入回收站",
        "delete_to_trash_sub" to "永久删除仍会二次确认",
        "auto_start_share" to "系统分享后自动启动",
        "auto_start_share_sub" to "收到文件后立即替换当前分享",
        "auto_stop" to "自动停止",
        "never" to "永不",
        "minutes_10" to "10分",
        "minutes_30" to "30分",
        "hour_1" to "1小时",
        "network_port" to "网络与端口",
        "preferred_port" to "首选端口（1024～65535）",
        "auto_find_port" to "自动寻找可用端口",
        "auto_find_port_sub" to "首选端口被占用时继续尝试",
        "copy_after_start" to "启动后复制地址",
        "copy_after_start_sub" to "磁贴、快捷方式和系统分享均适用",
        "system_shortcuts" to "系统快捷入口",
        "add_quick_tile" to "添加快捷设置磁贴",
        "request_pinned_success" to "已请求添加桌面快捷方式，请在系统弹窗中确认。",
        "request_pinned_unsupported" to "当前桌面不支持自动添加固定快捷方式。",
        "add_whole_to_home" to "添加“一键分享整个手机”到桌面",
        "version_tile_help" to "版本 {0} · 磁贴点击可启动或停止，长按进入设置。",
        "port_range_error" to "端口必须在 1024～65535 之间。",
        "save_settings" to "保存设置",
        "stop" to "停止",
        "copy" to "复制",
        "qr_code" to "二维码",
        "connections" to "连接",
        "send" to "发送",
        "receive" to "接收",
        "tasks" to "任务",
        "running" to "运行中",
        "starting" to "正在启动",
        "running_upload" to "运行中 · 可上传",
        "running_readonly" to "运行中 · 只读",
        "stopped" to "已停止",
        "tile_add_manual" to "请下拉快捷设置面板，点击编辑后手动添加 SpeedShareWeb。",
        "tile_added" to "快捷设置磁贴已添加。",
        "tile_exists" to "快捷设置磁贴已经存在。",
        "tile_not_added" to "没有添加磁贴。",
        "tile_package_error" to "添加失败：组件包名不匹配。",
        "tile_request_progress" to "已有添加请求正在进行。",
        "tile_component_error" to "添加失败：磁贴组件配置错误。",
        "tile_foreground_error" to "请保持 SpeedShareWeb 在前台后重试。",
        "tile_unsupported" to "系统不支持自动添加磁贴。",
        "tile_result" to "磁贴请求结果：{0}",
        "invalid_share_config" to "启动失败：没有收到有效的共享配置。",
        "cannot_read_share" to "启动失败：无法读取这批分享文件。",
        "unknown_error" to "未知错误",
        "start_failed" to "启动失败：{0}",
        "port_only" to "端口 {0}",
        "port_fallback" to "首选端口 {0} 被占用，已自动改用 {1}。",
        "server_started_detail" to "{0} · {1} · {2}ms",
        "waiting_lan" to "服务器已启动，正在等待局域网连接。",
        "background_timeout" to "系统后台运行时限已到，服务器已自动停止。",
        "server_running_waiting" to "服务器仍在运行，正在等待局域网连接。",
        "network_restored" to "局域网已恢复，访问地址已更新。",
        "address_changed" to "网络地址已变化，请使用新的地址或二维码。",
        "idle_stopped" to "长时间没有设备连接，服务器已自动停止。",
        "notification_channel" to "SpeedShareWeb 局域网服务器",
        "notification_channel_desc" to "显示局域网文件服务器的运行状态与控制按钮。",
        "mode_selected_count" to "单独分享 {0} 个文件",
        "mode_whole" to "整个手机目录",
        "mode_upload" to "可上传",
        "mode_readonly" to "只读",
        "mode_manage" to "可管理",
        "mode_server" to "局域网服务器",
        "notification_waiting" to "{0} · 等待局域网",
        "notification_speed" to "{0} · {1} 个任务 · {2}",
        "notification_switching" to "SpeedShareWeb 正在切换",
        "notification_running" to "SpeedShareWeb 正在运行",
        "open" to "打开",
        "copy_address" to "复制地址",
        "cannot_start_background" to "无法启动后台服务器：{0}",
        "unknown_device" to "未知设备",
        "op_waiting" to "等待执行",
        "op_processing" to "正在处理",
        "op_complete" to "操作完成",
        "op_cancelled" to "操作已取消",
        "op_cancelling" to "正在取消…",
        "op_server_stopping" to "服务器正在停止，任务即将取消。",
        "op_copy" to "复制",
        "op_move" to "移动",
        "op_trash" to "移入回收站",
        "op_delete" to "永久删除",
        "op_restore" to "恢复",
        "op_deleting" to "正在删除 {0}",
        "op_trashing" to "正在移入回收站 {0}",
        "op_restoring" to "正在恢复 {0}",
        "op_skipped_same" to "已跳过同一目录中的 {0}",
        "op_skipped" to "已跳过 {0}",
        "op_working" to "{0} {1}",
        "op_copy_delete_failed" to "复制完成，但原文件删除失败：{0}",
        "op_no_valid_files" to "没有有效的文件。",
        "op_target_missing" to "目标目录不存在。",
        "op_target_self" to "不能把目录移动或复制到自身。",
        "op_target_inside" to "目标目录不能位于源目录内部。",
        "op_cancelled_exception" to "操作已取消。",
        "trash_file_missing" to "文件不存在。",
        "trash_repeat" to "不能重复移入回收站。",
        "trash_source_delete_failed" to "原文件删除失败。",
        "trash_metadata_failed" to "回收站元数据写入失败。",
        "trash_entry_missing" to "回收站项目不存在。",
        "trash_metadata_corrupt" to "回收站元数据损坏。",
        "trash_content_missing" to "回收站内容不存在。",
        "trash_original_invalid" to "原始路径无效。",
        "trash_source_remove_failed" to "回收站源文件删除失败。",
        "trash_overwrite_failed" to "无法覆盖 {0}。",
        "trash_create_dir_failed" to "无法创建目录 {0}。",
        "unknown" to "未知",
        "web_selected_title" to "单独分享",
        "web_selected_sub" to "共 {0} 个文件 · 点击图片、视频、音频或 PDF 可在线预览",
        "web_phone_title" to "手机目录",
        "web_items" to "{0} 项",
        "web_empty" to "当前没有可显示的内容",
        "web_live" to "实时连接中",
        "web_connections" to "连接",
        "web_send_speed" to "发送速度",
        "web_receive_speed" to "接收速度",
        "web_active_tasks" to "活动任务",
        "web_no_transfers" to "当前没有正在传输的文件",
        "web_search" to "搜索当前页面",
        "web_sort_name" to "按名称",
        "web_sort_newest" to "最新优先",
        "web_sort_oldest" to "最早优先",
        "web_sort_large" to "大文件优先",
        "web_sort_small" to "小文件优先",
        "web_sort_type" to "按类型",
        "web_grid" to "网格",
        "web_list" to "列表",
        "web_connecting" to "正在连接 SpeedShareWeb…",
        "web_close" to "关闭",
        "web_download_original" to "下载原文件",
        "web_reconnected" to "已重新连接到 SpeedShareWeb",
        "web_live_connected" to "实时已连接",
        "web_reconnecting" to "正在重连",
        "web_connection_lost" to "连接已中断",
        "web_wait_server" to "连接已中断，正在等待手机服务器恢复…",
        "web_visible" to "当前显示 {0} 项",
        "web_selected_count" to "已选择 {0} 项",
        "web_upload_file_progress" to "第 {0}/{1} 个：{2} · {3}% · {4}/s",
        "web_network_failed" to "网络连接失败",
        "web_choose_or_drop" to "请先选择或拖入文件",
        "web_upload_done" to "上传完成，等待页面自动更新",
        "web_upload_failed" to "上传失败：{0}",
        "web_select_file_zip_folder" to "请选择至少一个文件。文件夹请使用 ZIP 打包下载。",
        "web_select_items" to "请先选择文件或文件夹",
        "web_zip_name" to "ZIP 文件名",
        "web_no_download_url" to "服务器没有返回下载地址。",
        "web_zip_failed" to "ZIP 准备失败：{0}",
        "web_new_folder_name" to "请输入新文件夹名称",
        "web_folder_created" to "文件夹已创建",
        "web_create_failed" to "创建失败：{0}",
        "web_manage_prompt" to "管理 {0}\n输入操作：rename / copy / move / trash / delete",
        "web_new_name" to "新名称",
        "web_rename_failed" to "重命名失败：{0}",
        "web_unsupported_action" to "不支持的操作",
        "web_choose_copy_target" to "选择复制目标",
        "web_choose_move_target" to "选择移动目标",
        "web_loading_folders" to "正在读取目录…",
        "web_target" to "目标：/{0}",
        "web_target_hint" to "选择当前目录，或继续进入子目录",
        "web_use_here" to "选择当前目录",
        "web_parent" to "上一级",
        "web_open_folder" to "进入",
        "web_load_failed" to "读取失败：{0}",
        "web_conflict_prompt" to "同名文件处理方式：rename=自动改名，overwrite=覆盖，skip=跳过",
        "web_copy_started" to "复制任务已开始",
        "web_move_started" to "移动任务已开始",
        "web_submit_failed" to "提交任务失败：{0}",
        "web_delete_permanent_confirm" to "将永久删除所选内容，无法恢复。继续吗？",
        "web_delete_trash_confirm" to "将所选内容移入 SpeedShareWeb 回收站。继续吗？",
        "web_delete_started" to "删除任务已开始",
        "web_delete_failed" to "删除失败：{0}",
        "web_trash" to "SpeedShareWeb 回收站",
        "web_loading" to "正在读取…",
        "web_trash_count" to "回收站项目 {0} 个",
        "web_restore_hint" to "恢复时默认自动改名，不覆盖现有文件",
        "web_empty_trash" to "回收站为空",
        "web_original_location" to "原位置：/{0} · {1} · {2}",
        "web_restore" to "恢复",
        "web_delete_forever" to "永久删除",
        "web_empty_trash_action" to "清空回收站",
        "web_restore_started" to "恢复任务已开始",
        "web_restore_failed" to "恢复失败：{0}",
        "web_delete_trash_item_confirm" to "永久删除这个回收站项目？",
        "web_empty_trash_confirm" to "永久清空 SpeedShareWeb 回收站？",
        "web_empty_failed" to "清空失败：{0}",
        "web_task_center" to "文件操作任务中心",
        "web_no_operations" to "暂无文件操作任务",
        "web_cancel" to "取消",
        "web_cancel_failed" to "取消失败：{0}",
        "web_device_offline" to "设备已离线",
        "web_network_offline" to "当前设备网络已断开",
        "web_manage" to "管理",
        "web_folder" to "文件夹",
        "web_video" to "视频",
        "web_audio" to "音频",
        "web_open" to "打开",
        "web_preview" to "预览",
        "web_download" to "下载",
        "web_new_folder" to "新建文件夹",
        "web_task_center_short" to "任务中心",
        "web_readonly_hint" to "远程管理已关闭：当前可浏览、预览、下载和批量打包",
        "web_move" to "移动",
        "web_move_trash" to "移入回收站",
        "web_permanent_delete" to "永久删除",
        "web_management_title" to "批量选择与文件管理",
        "web_batch_download_title" to "批量下载",
        "web_batch_download_hint" to "勾选文件后，可分别下载或打包为一个 ZIP 文件。",
        "web_current_folder" to "当前目录：/{0}",
        "web_select_all" to "全选／取消",
        "web_download_separately" to "分别下载",
        "web_zip_fast" to "ZIP高速打包",
        "web_zip_compress" to "ZIP压缩",
        "web_clear_selection" to "取消选择",
        "web_file_management" to "文件管理",
        "web_internal_storage" to "内部存储",
        "web_upload_here" to "上传到当前文件夹",
        "web_upload_hint" to "可选择多个文件，也可以直接把文件拖到这里",
        "web_choose_files" to "选择文件",
        "web_start_upload" to "开始上传",
        "web_no_files_selected" to "尚未选择文件",
        "web_state_queued" to "等待中",
        "web_state_running" to "进行中",
        "web_state_completed" to "已完成",
        "web_state_failed" to "失败",
        "web_state_cancelled" to "已取消"
    )

}

fun operationKindText(kind: FileOperationKind, translator: Translator): String = when (kind) {
    FileOperationKind.COPY -> translator.text("op_copy")
    FileOperationKind.MOVE -> translator.text("op_move")
    FileOperationKind.TRASH -> translator.text("op_trash")
    FileOperationKind.DELETE -> translator.text("op_delete")
    FileOperationKind.RESTORE -> translator.text("op_restore")
}
